import React, { useState } from 'react';
import styles from "../../styles/Home.module.css";
import LoginForm from "../../src/components/auth/LoginForm";
import Head from "next/head";
import Header from "../../src/components/Layout/Header";
import Footer from "../../src/components/Layout/Footer";
function auth() {

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/** 헤더 **/}
            <Header />

            {/** 콘텐츠 부분 **/}
            <LoginForm />

            {/** 푸터 부분 **/}
            <Footer />
        </div>
    )
}

export default auth;