import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Footer from "../src/components/Layout/Footer";
import Header from "../src/components/Layout/Header";

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a onClick={()=>{console.log("dd")}}>Travelog!</a>
        </h1>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Make your own travelog &rarr;</h2>
            <p>If you input the places you have visited, We'll create your log.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Share your travelog &rarr;</h2>
            <p>Share your travel log with people and me!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Travel Planner &rarr;</h2>
            <p>Record your travel plans and expense ledger.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2></h2>
            <h2>Travel Maker &rarr;</h2>
            <p>
              Provide a list of travel-related websites and recommend itineraries.
            </p>
          </a>
        </div>
      </main>
      <Footer />
    </div>
  )
}
